apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - name: web
      port: {{ .Values.api.port }}